services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #   - "3000:3000"
  gandalf:
    build: ./gandalf
    ports:
      - "8000:8000"
  snitch:
    build: ./snitch
    ports:
      - "8001:8001"