services:
  frontend:
    build: ./frontend
    ports:
    - "3000:3000"
  gandalf:
    build: ./gandalf
    ports:
      - "8000:8000"
  snitch:
    build: ./snitch
    ports:
      - "8001:8001"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "aquahelp"
    ports:
      - "3306:3306"
  filestorage:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: "minio"
      MINIO_SECRET_KEY: "minio"
    ports:
      - "9000:9000"
    volumes:
      - ./filestorage/data:/data
      - ./filestorage/config:/root/.minio